lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser_common do
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {CodeStatsWeb.LayoutView, :root})
    plug(:put_secure_browser_headers)
    plug(:protect_from_forgery)
    plug(CodeStatsWeb.RememberMePlug)
    plug(CodeStatsWeb.SetSessionUserPlug)
    plug(CodeStatsWeb.AdPlug)
    plug(CodeStatsWeb.ConsentPlug)
  end

  pipeline :browser_html do
    plug(:accepts, ["html"])
  end

  pipeline :browser_csv do
    plug(:accepts, ["csv"])
  end

  pipeline :browser_auth do
    plug(CodeStatsWeb.AuthRequiredPlug)
  end

  pipeline :browser_unauth do
    plug(CodeStatsWeb.AuthNotAllowedPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :browser_api do
    plug(:fetch_session)
    plug(CodeStatsWeb.SetSessionUserPlug)
  end

  pipeline :api_machine_auth do
    plug(CodeStatsWeb.MachineAuthRequiredPlug)
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_html)
    pipe_through(:browser_common)

    get("/", PageController, :index)

    get("/api-docs", PageController, :api_docs)
    get("/tos", PageController, :terms)
    get("/plugins", PageController, :plugins)
    get("/changes", ChangesController, :changes)
    get("/support", SupportController, :page)

    get("/aliases", AliasController, :list)

    get("/battle", BattleController, :battle)

    scope "/" do
      pipe_through(:browser_unauth)

      get("/login", AuthController, :render_login)
      post("/login", AuthController, :login)
      get("/signup", AuthController, :render_signup)
      post("/signup", AuthController, :signup)
      get("/forgot-password", AuthController, :render_forgot)
      post("/forgot-password", AuthController, :forgot)
      get("/reset-password/:token", AuthController, :render_reset)
      put("/reset-password/:token", AuthController, :reset)
    end

    get("/logout", AuthController, :logout)

    live("/users/:username", ProfileLive, :profile_live)
    get("/users/:username/avatar", ProfileController, :profile_gravatar)

    scope "/my" do
      pipe_through(:browser_auth)

      get("/profile", ProfileController, :my_profile)

      get("/preferences", PreferencesController, :edit)
      put("/preferences", PreferencesController, :do_edit)
      delete("/preferences", PreferencesController, :delete)

      get("/machines", MachineController, :list)
      post("/machines", MachineController, :add)
      get("/machines/:id", MachineController, :view_single)
      put("/machines/:id", MachineController, :edit)
      delete("/machines/:id", MachineController, :delete)
      post("/machines/:id/activate", MachineController, :activate)
      post("/machines/:id/deactivate", MachineController, :deactivate)
      post("/machines/:id/key", MachineController, :regen_machine_key)

      get("/consent", TermsController, :ask_consent)
      post("/consent", TermsController, :set_consent)
      delete("/consent-delete", TermsController, :delete_account)
    end
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_csv)
    pipe_through(:browser_common)
    pipe_through(:browser_auth)

    get("/my/pulses", PulseController, :list)
    get("/my/private", ProfileController, :export_private)
  end

  scope "/" do
    pipe_through(:api)
    pipe_through(:browser_api)

    forward("/profile-graph", Absinthe.Plug, schema: CodeStats.Profile.PublicSchema)
    forward("/profile-graphiql", Absinthe.Plug.GraphiQL, schema: CodeStats.Profile.PublicSchema)
  end

  scope "/api", CodeStatsWeb do
    pipe_through(:api)

    get("/users/:username", ProfileController, :profile_api)

    scope "/my" do
      pipe_through(:api_machine_auth)

      post("/pulses", PulseController, :add)
    end
  end
end

lib/code_stats_web/templates/page/api_docs.html.eex
<div class="stripe">
  <h1>
    API documentation <sup>(v. 1.0.1)</sup>
  </h1>

  <h2>
    Table of Contents
  </h2>

  <p>
    <ol>
      <li>
        <a href="#basics">Basics</a>
      </li>
      <li>
        <a href="#terms">Terms</a>
      </li>
      <li>
        <a href="#auth">Authentication</a>
      </li>
      <li>
        <a href="#profile">Endpoint: Profile</a>
      </li>
      <li>
        <a href="#pulse">Endpoint: Pulse</a>
      </li>
    </ol>
  </p>

  <h2>
    Basics <a id="basics" href="#basics">#</a>
  </h2>

  <h3>Beta</h3>

  <p>
    For all your API testing needs, especially when testing adding new XP into the system, use the <a href="https://beta.codestats.net/" target="_blank">beta instance</a>.
  </p>

  <h3>API version</h3>

  <p>
    The API follows <a href="http://semver.org/">Semantic Versioning</a>. That means bugfixes bump the patch version, backwards compatible features bump the minor version and backwards incompatible changes bump the major version.
  </p>

  <h3>Protocol</h3>

  <p>
    All requests are made using HTTP and use JSON to serialize the data. Requests with payloads should send the payload as JSON in the request body. The responses are JSON, error responses will contain the key <code>error</code> which has the error message as value. The error message is a human readable message, not intended for automated parsing.
  </p>

  <h3>Path</h3>

  <p>
    All API paths are prefixed with <code>/api</code>.
  </p>

  <h3>HTTPS</h3>

  <p>
    All requests must be secured using HTTPS. Plain HTTP requests will not be accepted.
  </p>

  <h3>Timestamps</h3>

  <p>
    Datetime timestamps should be sent as RFC 3339 datetime values and include the timezone offset. Example: <code>2016-04-24T01:43:56+12:00</code>.
  </p>

  <h2>
    Terms <a id="terms" href="#terms">#</a>
  </h2>

  <h3>XP</h3>

  <p>
    Programming gives users <em>experience points</em>, i.e. XP. A certain amount of XP corresponds to a certain level. In Code::Stats, each keystroke that creates or deletes a character gives 1 XP, so a client should keep an XP counter and add to it on each such keystroke. Operating on many characters at once, such as when deleting highlighted text, is counted as 1 XP, if made possible by the editor's API. An XP value is a positive integer.
  </p>

  <h3>Level</h3>

  <p>
    A <em>level</em> is a human readable indicator of progress. It is calculated from XP and its only purpose is to make an amount of XP more meaningful for a user. The read API does not provide levels, so it is the client's job to calculate the levels of a user.
  </p>

  <p>
    Levels are calculated with the following pseudocode formula:
  </p>

  <pre><code>LEVEL_FACTOR = 0.025

// Get level for given XP
int get_level(float xp) {
  return to_int(floor(LEVEL_FACTOR * sqrt(xp)))
}</code></pre>

  <p>
    For more examples of level calculations, see <a href="https://gitlab.com/code-stats/code-stats/-/blob/master/lib/code_stats/xp/xp_calculator.ex">CodeStats.Language.XPCalculator</a>.
  </p>

  <h3>Language</h3>

  <p>
    XP is always tied to a <em>language</em>. This can be a programming language, but also some other syntax edited by the users, such as Markdown or JSON. Detecting the active language is the client's responsibility. This can be done, for example, based on the active syntax highlighting language or the file's extension. Languages are referred to by their names as strings.
  </p>

  <h3>Pulse</h3>

  <p>
    A <em>pulse</em> is a collection of XPs for different languages. Pulses should be added periodically by the client and should contain the languages used and the XPs accumulated since the last pulse. They should also contain the time the pulse was created. This way they can be sent later, if the user's Internet connection is down for the moment. Pulses that are more than a week old will not be accepted by the API.
  </p>

  <h2>
    Authentication <a id="auth" href="#auth">#</a>
  </h2>

  <p>
    Code::Stats uses simple token authentication. A single token authenticates both a user and the machine they are using. It is signed to prevent tampering and unauthorized creation of tokens matching other users' information. To generate a token, you need to create a new machine from the <a href="<%= Routes.machine_path(@conn, :list) %>">Machine control panel</a>. A token looks like this:
  </p>

  <pre><code>SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ</code></pre>

  <p>
    In all API requests that require authentication, the token must be added using the HTTP header <code>X-API-Token</code>. Here is an example request sent with the token (as printed by curl):
  </p>

  <pre><code>&gt; POST /api/my/pulses HTTP/1.1
&gt; Host: codestats.net:443
&gt; User-Agent: curl/7.43.0
&gt; Accept: */*
&gt; X-API-Token: SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ
&gt; Content-Type: application/json
&gt; Content-Length: 113</code></pre>

  <h2>
    Endpoint: Profile <a id="profile" href="#profile">#</a>
  </h2>

  <h3>
    Read public user's information
  </h3>

  <p>
    <code>GET <%= Routes.profile_path(@conn, :profile_api, "username") %></code>
  </p>

  <p>
    Retrieves the information of the specified user. If the user does not exist or their profile is private, <code>HTTP 404</code> will be returned. An example request that also shows the returned data format:
  </p>

  <pre><code>GET /api/users/Nicd HTTP/1.1

{
  "user": "Nicd",
  "total_xp": 3073421,
  "new_xp": 3289,
  "machines": {
    "Työkone": {
      "xps": 246116,
      "new_xps": 3289
    },
    "Best Machine": {
      "xps": 2827305,
      "new_xps": 0
    }
  },
  "languages": {
    "💩": {
      "xps": 1767278,
      "new_xps": 0
    },
    "XML": {
      "xps": 15,
      "new_xps": 0
    },
    "Plaintext": {
      "xps": 3429,
      "new_xps": 3289
    }
  },
  "dates": {
    "2016-12-31": 3289,
    "2016-08-24": 26700
  }
}</code></pre>

  <p>
    <strong>Returns</strong> user profile data as JSON. In the data, <code>new_xps</code> is XP gained in the last 12 hours.
  </p>

  <h2>
    Endpoint: Pulse <a id="pulse" href="#pulse">#</a>
  </h2>

  <h3>
    Add pulse <sup>(authn required)</sup>
  </h3>

  <p>
    <code>POST <%= Routes.pulse_path(@conn, :add) %></code>
  </p>

  <p>
    Adds a new <em>Pulse</em> to the system. The client should send a pulse periodically when the user is programming. The payload should be a list of languages and their accumulated XP since the last successful pulse. The pulse must also contain a <code>coded_at</code> timestamp that signifies when the pulse was generated. This allows sending the pulse later, if the Internet connection is momentarily cut.
  </p>

  <p>
    <strong>Note:</strong> The <code>coded_at</code> timestamp <strong>MUST</strong> be in the user's local time with their local UTC offset. Do not convert the time to UTC before sending it to the API.
  </p>

  <p>
    Note: The <code>coded_at</code> timestamp must be no older than a week. Any older timestamps will result in an error. Timestamps in the future will be ignored, their <code>coded_at</code> will be set to the current moment.
  </p>

  <p>
    Example payload:
  </p>

  <pre><code>{
  "coded_at": "2016-04-24T01:43:56+12:00",
  "xps": [
    {"language": "C++",    "xp": 15},
    {"language": "Elixir", "xp": 30},
    {"language": "EEx",    "xp": 3}
  ]
}</code></pre>

  <p><strong>Returns</strong> <code>HTTP 201</code> and <code>{"ok": "Great success!"}</code> on success.</p>
</div>

lib/code_stats_web/templates/page/plugins.html.eex
<%
  plugin_icon = fn img, editor ->
    render(
      CodeStatsWeb.ComponentsView,
      "picture.html",
      conn: @conn,
      src: "/assets/frontend/images/#{img}",
      alt: "#{editor} logo",
      title: editor,
      class: "plugin-image"
    )
  end
%>

<div class="stripe">
  <h1>
    <%= get_conf(:site_name) %> plugins
  </h1>

  <div class="plugin-icon-list">
    <a href="#atom">
      <img
       class="plugin-image"
       src="<%= Routes.static_path(@conn, "/assets/frontend/images/atom-logo.svg") %>"
       title="Atom editor"
       alt="Atom editor logo"
      />
    </a>
    <a href="#browsers">
      <%= plugin_icon.("code-stats-browser-logo.png", "Browsers") %>
    </a>
    <a href="#jetbrains">
      <img
       class="plugin-image"
       src="<%= Routes.static_path(@conn, "/assets/frontend/images/jetbrains-logo.svg") %>"
       title="JetBrains"
       alt="JetBrains logo"
      />
    </a>
    <a href="#lazarus">
      <%= plugin_icon.("lazarus-logo.png", "Lazarus IDE") %>
    </a>
    <a href="#st3">
      <%= plugin_icon.("sublime-logo.png", "Sublime Text") %>
    </a>
    <a href="#vim">
      <%= plugin_icon.("vim-logo.gif", "Vim") %>
    </a>
    <a href="#vb6">
      <%= plugin_icon.("vb6icon_cropped_transparent.png", "Visual Basic 6.0") %>
    </a>
    <a href="#vs">
      <img
       class="plugin-image"
       src="<%= Routes.static_path(@conn, "/assets/frontend/images/vs-logo.svg") %>"
       title="Visual Studio"
       alt="Visual Studio logo"
      />
    </a>
    <a href="#vscode">
      <%= plugin_icon.("vscode-logo.png", "Visual Studio Code") %>
    </a>
    <a href="#zsh">
      <%= plugin_icon.("zsh-logo.png", "Zsh") %>
    </a>
  </div>

  <h2>A note about the functionality of the plugins</h2>

  <p>
    The plugins work by listening to your editor's text changes and detecting the syntax used. If you are having problems with XP registering to the wrong language, you may need to install an appropriate language support package for your editor. <%= get_conf(:site_name) %> relies on the editor to detect the proper language.
  </p>

  <p>
    Note that <em>at no point is any of your code sent to <%= get_conf(:site_name) %></em>. Only the amounts of XP (roughly the amount of keystrokes) are sent. For further information, check the <a href="<%= Routes.page_path(@conn, :api_docs) %>">API documentation</a> and the source code of the plugins.
  </p>

  <hr />

  <div class="plugin">
    <h2 id="atom">Atom</h2>

    <div class="plugin-description">
      <p>
        To install, use Atom's builtin package search to search for <code>code-stats-atom</code> and install the package. Then go to the package's settings page and insert the API key of the machine you want.
      </p>

      <p>
        <a target="_blank" href="https://atom.io/packages/code-stats-atom">Link to the plugin on Atom's site.</a>
      </p>
    </div>

    <img
     class="plugin-image"
     src="<%= Routes.static_path(@conn, "/assets/frontend/images/atom-logo.svg") %>"
     title="Atom editor"
     alt="Atom editor logo"
    />
  </div>

  <div class="plugin">
    <h2 id="browsers">Browsers (Chrome, Edge, Firefox)</h2>

    <div class="plugin-description">
      <p>
        To install, find the correct extension for your browser from the list below. Then insert your API key into the extension settings, after clicking on the "C::S" extension button.
      </p>

      <p>
        <ul>
          <li><strong>Chrome / Edge:</strong> Install from <a target="_blank" href="https://chrome.google.com/webstore/detail/code-stats-chrome-extensi/ljecglgmlhpjalfccaojplcidlmaochd">Chrome Web Store</a>.</li>
          <li><strong>Firefox:</strong> Install from <a target="_blank" href="https://addons.mozilla.org/en/firefox/addon/code-stats-extension/?src=search">Firefox Add-ons store</a>.</li>
        </ul>
      </p>

      <p>
        <a target="_blank" href="https://gitlab.com/code-stats/code-stats-browser">Link to the repository on GitLab.</a>
      </p>

      <p>
        <em>Thanks to Finn Dohrn (bitnulleins) for the browser extensions.</em>
      </p>
    </div>

    <%= plugin_icon.("code-stats-browser-logo.png", "Browsers") %>
  </div>

  <div class="plugin">
    <h2 id="jetbrains">JetBrains IDEs</h2>

    <div class="plugin-description">
      <p>
        To install, use the IDE's builtin package manager, click on "Browse repositories…" and search for <code>Code::Stats</code> or <code>CodeStats</code>. After installation, go to Settings → Other Settings → Code::Stats and insert your API key.
      </p>

      <p>
        <a target="_blank" href="https://plugins.jetbrains.com/plugin/8393?pr=">Link to the plugin on JetBrain's site.</a>
      </p>

      <p>
        <strong>Note:</strong>
        If the plugin fails to send XP, reporting <code>C::S ERR!</code>, hover over the status bar text to see the actual exception. If it complains of a PKIX error, you may need to install the <a href="https://www.identrust.com/certificates/trustid/root-download-x3.html">DST Root CA X3</a> to the IDE's JRE's trust store manually. The command to do that goes roughly like this on macOS:
      </p>

      <pre><kbd>$ cd /Applications/&lt;IDE&gt;.app/Contents/jre/jdk/Contents/Home/jre
$ bin/keytool -import -alias 'DST Root CA X3' -keystore lib/security/cacerts -trustcacerts -file /path/to/dst_root_ca_x3.pem</kbd></pre>
    </div>

    <img
     class="plugin-image"
     src="<%= Routes.static_path(@conn, "/assets/frontend/images/jetbrains-logo.svg") %>"
     title="JetBrains"
     alt="JetBrains logo"
    />
  </div>

  <div class="plugin">
    <h2 id="lazarus">Lazarus IDE</h2>

    <div class="plugin-description">
      <p>
        You can find the plugin in Lazarus IDE's Online Package Manager by searching for <code>CodeStats</code>.
      </p>

      <p>
        You can find further installation and setup instructions <a target="_blank" href="https://github.com/maico-smaniotto/codestats-pkg-lazarus">in the project's GitHub repository</a>.
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="https://github.com/maico-smaniotto">Maico Smaniotto</a> for the Lazarus IDE extension.</em>
      </p>
    </div>

    <%= plugin_icon.("lazarus-logo.png", "Lazarus IDE") %>
  </div>

  <div class="plugin">
    <h2 id="st3">Sublime Text 3</h2>

    <div class="plugin-description">
      <p>
        To install, first setup <a href="https://packagecontrol.io/">Package Control</a> and then use it to install package <code>CodeStats</code>. Then open the package settings and configure the API key.
      </p>

      <p>
        <a target="_blank" href="https://packagecontrol.io/packages/CodeStats">Link to the plugin on Package Control's site.</a>
      </p>
    </div>

    <%= plugin_icon.("sublime-logo.png", "Sublime Text") %>
  </div>

  <div class="plugin">
    <h2 id="vim">Vim</h2>

    <div class="plugin-description">
      <p>
        You can find installation and setup instructions <a target="_blank" href="https://gitlab.com/code-stats/code-stats-vim">in the project's GitLab repository</a>.
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="https://github.com/dancek">Hannu Hartikainen</a> and Antti Keränen for the Vim extension.</em>
      </p>
    </div>

    <%= plugin_icon.("vim-logo.gif", "Vim") %>
  </div>

  <div class="plugin">
    <h2 id="vb6">Visual Basic 6.0</h2>

    <div class="plugin-description">
      <p>
        To install, see instructions on plugin's webpage. <a target="_blank" href="https://bitbucket.org/Koohiisan/code-stats-vb6-add-in">Link to the plugin on Bitbucket.</a>
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="https://www.lukegerhardt.com/">Luke Gerhardt</a> for the VB6 extension.</em>
      </p>
    </div>

    <%= plugin_icon.("vb6icon_cropped_transparent.png", "Visual Basic 6.0") %>
  </div>

  <div class="plugin">
    <h2 id="vs">Visual Studio</h2>

    <div class="plugin-description">
      <p>
        To install, download the proper extension from the Visual Studio Marketplace. and run the installer. After installation, go to Extras → Options → CodeStats and insert your API key.
      </p>

      <p>
        <ul>
          <li>For VS2022: <a href="https://marketplace.visualstudio.com/items?itemName=ScratchCat.CodeStatsForVS">https://marketplace.visualstudio.com/items?itemName=ScratchCat.CodeStatsForVS</a></li>
          <li>For older versions: <a href="https://marketplace.visualstudio.com/items?itemName=MathiasSTorm.CodeStatsClient">https://marketplace.visualstudio.com/items?itemName=MathiasSTorm.CodeStatsClient</a></li>
        </ul>
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="https://github.com/mastorm">Mathias Storm</a> and <a target="_blank" href="https://github.com/AlaiyaNetwork">
Andrey Belov</a> for the Visual Studio extensions.</em>
      </p>
    </div>

    <img
     class="plugin-image"
     src="<%= Routes.static_path(@conn, "/assets/frontend/images/vs-logo.svg") %>"
     title="Visual Studio"
     alt="Visual Studio logo"
    />
  </div>

  <div class="plugin">
    <h2 id="vscode">Visual Studio Code</h2>

    <div class="plugin-description">
      <p>
        To install, use the editor's extension manager and search for <code>CodeStats</code>. After installating the extension and reloading the editor, set the <code>codestats.apikey</code> setting to your API key.
      </p>

      <p>
        <a target="_blank" href="https://marketplace.visualstudio.com/items?itemName=riussi.code-stats-vscode">Link to the plugin in the Visual Studio Marketplace.</a>
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="http://www.juharistolainen.com/">Juha Ristolainen</a> for the VSCode extension.</em>
      </p>
    </div>

    <%= plugin_icon.("vscode-logo.png", "Visual Studio Code") %>
  </div>

  <div class="plugin">
    <h2 id="zsh">Zsh</h2>

    <div class="plugin-description">
      <p>
        You can find installation and setup instructions <a target="_blank" href="https://gitlab.com/code-stats/code-stats-zsh">in the project's GitLab repository</a>.
      </p>

      <p>
        <em>Thanks to <a target="_blank" href="https://github.com/dancek">Hannu Hartikainen</a> for the Zsh extension.</em>
      </p>
    </div>

    <%= plugin_icon.("zsh-logo.png", "Zsh") %>
  </div>

  <div class="media">
    <div class="media-body">
      <h2 class="media-heading">Other editors</h2>

      <p>
        If there is no plugin for your favourite editor, you can check out the <a href="<%= Routes.page_path(@conn, :api_docs) %>">API docs</a> and implement one yourself. If you do, please let us know so we can add a link to it here!
      </p>
    </div>

    <hr />

    <p>
      <em>
        All logos are the intellectual property and possible trademarks of their respective owners. The Atom editor logo is licensed under the MIT licence. The JetBrains logo is used with permission from JetBrains s.r.o. The Notepad++ logo (© Dan Ho) is licensed under CC-BY-SA 3.0. It is believed that the rest of the logos are used according to the fair use rules of Finnish law.
      </em>
    </p>
  </div>
</div>

lib/code_stats_web/templates/page/terms_page.html.eex
<div class="stripe" id="terms-stripe">
  <h1>Legal matters</h1>

  <%= render(CodeStatsWeb.PageView, "terms.html") %>
</div>