lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser_common do
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {CodeStatsWeb.LayoutView, :root})
    plug(:put_secure_browser_headers)
    plug(:protect_from_forgery)
    plug(CodeStatsWeb.RememberMePlug)
    plug(CodeStatsWeb.SetSessionUserPlug)
    plug(CodeStatsWeb.AdPlug)
    plug(CodeStatsWeb.ConsentPlug)
  end

  pipeline :browser_html do
    plug(:accepts, ["html"])
  end

  pipeline :browser_csv do
    plug(:accepts, ["csv"])
  end

  pipeline :browser_auth do
    plug(CodeStatsWeb.AuthRequiredPlug)
  end

  pipeline :browser_unauth do
    plug(CodeStatsWeb.AuthNotAllowedPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :browser_api do
    plug(:fetch_session)
    plug(CodeStatsWeb.SetSessionUserPlug)
  end

  pipeline :api_machine_auth do
    plug(CodeStatsWeb.MachineAuthRequiredPlug)
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_html)
    pipe_through(:browser_common)

    get("/", PageController, :index)

    get("/api-docs", PageController, :api_docs)
    get("/tos", PageController, :terms)
    get("/plugins", PageController, :plugins)
    get("/changes", ChangesController, :changes)
    get("/support", SupportController, :page)

    get("/aliases", AliasController, :list)

    get("/battle", BattleController, :battle)

    scope "/" do
      pipe_through(:browser_unauth)

      get("/login", AuthController, :render_login)
      post("/login", AuthController, :login)
      get("/signup", AuthController, :render_signup)
      post("/signup", AuthController, :signup)
      get("/forgot-password", AuthController, :render_forgot)
      post("/forgot-password", AuthController, :forgot)
      get("/reset-password/:token", AuthController, :render_reset)
      put("/reset-password/:token", AuthController, :reset)
    end

    get("/logout", AuthController, :logout)

    live("/users/:username", ProfileLive, :profile_live)
    get("/users/:username/avatar", ProfileController, :profile_gravatar)

    scope "/my" do
      pipe_through(:browser_auth)

      get("/profile", ProfileController, :my_profile)

      get("/preferences", PreferencesController, :edit)
      put("/preferences", PreferencesController, :do_edit)
      delete("/preferences", PreferencesController, :delete)

      get("/machines", MachineController, :list)
      post("/machines", MachineController, :add)
      get("/machines/:id", MachineController, :view_single)
      put("/machines/:id", MachineController, :edit)
      delete("/machines/:id", MachineController, :delete)
      post("/machines/:id/activate", MachineController, :activate)
      post("/machines/:id/deactivate", MachineController, :deactivate)
      post("/machines/:id/key", MachineController, :regen_machine_key)

      get("/consent", TermsController, :ask_consent)
      post("/consent", TermsController, :set_consent)
      delete("/consent-delete", TermsController, :delete_account)
    end
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_csv)
    pipe_through(:browser_common)
    pipe_through(:browser_auth)

    get("/my/pulses", PulseController, :list)
    get("/my/private", ProfileController, :export_private)
  end

  scope "/" do
    pipe_through(:api)
    pipe_through(:browser_api)

    forward("/profile-graph", Absinthe.Plug, schema: CodeStats.Profile.PublicSchema)
    forward("/profile-graphiql", Absinthe.Plug.GraphiQL, schema: CodeStats.Profile.PublicSchema)
  end

  scope "/api", CodeStatsWeb do
    pipe_through(:api)

    get("/users/:username", ProfileController, :profile_api)

    scope "/my" do
      pipe_through(:api_machine_auth)

      post("/pulses", PulseController, :add)
    end
  end
end

lib/code_stats_web/views/layout_view.ex
defmodule CodeStatsWeb.LayoutView do
  use CodeStatsWeb, :view

  def get_title(conn) do
    site_name = get_conf(:site_name)

    if conn.assigns[:title] do
      "#{conn.assigns[:title]} – #{site_name}"
    else
      site_name
    end
  end

  @doc """
  Check if user is authenticated. If session is not fetched, return false.
  """
  def is_authed?(conn) do
    try do
      CodeStatsWeb.AuthUtils.is_authed?(conn)
    rescue
      _ -> false
    end
  end

  @doc """
  Get flash of given type if fetched, otherwise returns nil.
  """
  def get_flash(conn, type) do
    try do
      Phoenix.Controller.get_flash(conn, type)
    rescue
      _ -> nil
    end
  end
end

lib/code_stats_web/templates/layout/battle.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Code::Stats is a free stats tracking service for programmers">
    <meta name="author" content="Mikko Ahlroth">

    <title><%= get_conf(:site_name) %> Battle Mode</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/battle/css/battle.css") %>">

    <link rel="apple-touch-icon" sizes="57x57" href="/frontend/assets/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/frontend/assets/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/frontend/assets/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/frontend/assets/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/frontend/assets/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/frontend/assets/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/frontend/assets/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/frontend/assets/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/frontend/assets/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/frontend/assets/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/frontend/assets/manifest.json">
    <link rel="mask-icon" href="/frontend/assets/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/frontend/assets/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= if is_authed?(@conn) do %>
      <%= tag(:meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", get_current_user(@conn).username)) %>
    <% end %>
  </head>

  <body>
    <%= @inner_content %>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/battle/js/battle.js") %>"></script>
    <%= raw get_conf(:analytics_code) %>
  </body>
</html>

lib/code_stats_web/templates/layout/email.text.eex
<%= get_conf(:site_name) %>
===========

<%= @inner_content %>

-----------
This email was sent from <%= get_conf(:site_name) %> <<%= Routes.page_url(CodeStatsWeb.Endpoint, :index) %>>. If you do not wish to receive more emails, you can remove your email address in the preferences page of your account.

Please note that you cannot reply to this email.